from turtle import *
Window = Screen()
Window = title("Pyng")
Window = bgcolor("#00ff43")
Window = setup(1000,450)
topBar = Turtle()
topBar.shape("square")
topBar.pensize(15)
topBar.color("#0073d8")
topBar.up()
topBar.hideturtle()
topBar.goto(460,190)
topBar.down()
topBar.goto(-465,190)
lowerBar = Turtle()
lowerBar.shape("square")
lowerBar.pensize(15)
lowerBar.color("#0073d8")
lowerBar.up()
lowerBar.hideturtle()
lowerBar.goto(-465,-190)
lowerBar.down()
lowerBar.goto(465,-190)
mainloop()